'use strict';
const $ = id => document.getElementById(id);
const NS = 'http://www.w3.org/2000/svg';
const state = {map:null,points:[],routes:[],sessions:[],total:0,offset:0,health:null,mode:'inspect',page:'map',references:'points',waypoints:[],draft:null,zoom:1,session:null,replay:null,annotations:[],playing:false,position:0,selection:0,capture:null,captureTimer:null};
const titles = {map:['Apartment map','A place for every experiment.','Map your space, mark a reference point, and make your next session repeatable.'],sessions:['Sessions & replay','Turn recordings into observations.','Review saved signals, inspect gaps, and add your own timed reference labels.'],devices:['Devices & system','Know what your setup can see.','Documented devices, approximate placement, and the limits of the current system.']};
let toastTimer, playbackFrame, lastPlayback;
function applyTheme(theme){document.documentElement.dataset.theme=theme;const dark=theme==='dark';$('theme-toggle').textContent=dark?'☀':'☾';$('theme-toggle').setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');$('theme-toggle').title=dark?'Switch to light theme':'Switch to dark theme';localStorage.setItem('ruview-theme',theme);}
function element(tag, text, className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function svg(tag, attrs, text){const e=document.createElementNS(NS,tag);for(const [key,value] of Object.entries(attrs||{}))e.setAttribute(key,value);if(text!==undefined)e.textContent=text;return e;}
function empty(target,message){$(target).replaceChildren(element('p',message,'empty'));}
function toast(message,error=false){$('toast').textContent=message;$('toast').className='toast'+(error?' error':'');$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
function errorBanner(message){$('error-banner').textContent=message;$('error-banner').hidden=!message;}
function num(value,digits=1){return Number.isFinite(value)?value.toFixed(digits):'—';}
function bytes(value){return value>=1024**3?`${num(value/1024**3)} GB`:`${num(value/1024**2)} MB`;}
function date(value){return value?new Date(value).toLocaleString(undefined,{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Unknown date';}
async function api(path,body){const options={signal:AbortSignal.timeout(20000)};if(body!==undefined)Object.assign(options,{method:'POST',headers:{'Content-Type':'application/json','X-Panel-Token':state.health?.write_token||''},body:JSON.stringify(body)});const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function renderLive(samples=[]){const chart=$('live-signal-chart');if(!chart)return;chart.replaceChildren();const valid=samples.filter(s=>s.valid&&s.smooth!==null);if(!valid.length)return;const max=Math.max(.1,...valid.map(s=>s.smooth||0))*1.12,duration=Math.max(1,valid.at(-1).seconds),x=t=>48+t/duration*734,y=v=>125-v/max*95;for(let i=0;i<=4;i++){const value=max*i/4;chart.append(svg('line',{x1:48,y1:y(value),x2:782,y2:y(value)}));}let path='';for(const s of valid)path+=`${path?'L':'M'}${x(s.seconds).toFixed(2)},${y(s.smooth).toFixed(2)} `;chart.append(svg('path',{d:path}));}
function renderCapture(){const c=state.capture;if(!c){$('capture-status').textContent='Ready';$('capture-pause').disabled=true;$('capture-resume').disabled=true;$('capture-stop').disabled=true;$('capture-delete').disabled=!state.session;return;}const status=c.session.status;$('capture-status').textContent=c.paused?'Paused':status;$('capture-message').textContent=`Session ${c.session.id.slice(0,8)} · ${c.session.records} records · ${c.remaining_s??'—'} s remaining`;$('capture-pause').disabled=!!c.paused||status!=='running';$('capture-resume').disabled=!c.paused;$('capture-stop').disabled=!['running','paused'].includes(status);$('capture-delete').disabled=!['captured','stopped','failed'].includes(status);renderLive(c.samples||[]);}
async function pollCapture(){if(!state.capture)return;try{const c=await api(`/api/captures/${encodeURIComponent(state.capture.id)}`);state.capture=c;renderCapture();if(['running','paused'].includes(c.session.status)){state.captureTimer=setTimeout(pollCapture,1000);}else{state.captureTimer=null;await load();}}catch(e){try{const detail=await api(`/api/sessions/${encodeURIComponent(state.capture.id)}`);const replay=await api(`/api/sessions/${encodeURIComponent(state.capture.id)}/measurements`);state.capture={id:state.capture.id,session:detail.session,annotations:detail.annotations,samples:replay.samples,paused:false};renderCapture();if(['running','paused'].includes(detail.session.status))state.captureTimer=setTimeout(pollCapture,1000);else{state.captureTimer=null;await load();}}catch(fallback){$('capture-message').textContent=`Capture status unavailable: ${fallback.message}`;state.captureTimer=setTimeout(pollCapture,1500);}}}
async function startCapture(){try{const result=await api('/api/captures',{seconds:Number($('capture-seconds').value),interval_ms:Number($('capture-interval').value)});state.capture={id:result.session,session:{id:result.session,status:'running',records:0},paused:false,remaining_s:Number($('capture-seconds').value)};renderCapture();pollCapture();toast('Recording started on the Raspberry Pi.');}catch(e){toast(e.message,true);}}
async function captureAction(action){if(!state.capture)return;try{await api(`/api/captures/${encodeURIComponent(state.capture.id)}/${action}`,{});if(action==='stop')toast('Stopping recording and cleaning up the router monitor.');pollCapture();}catch(e){toast(e.message,true);}}
async function deleteSession(id){if(!id||!confirm('Delete this session, its raw CSI records and labels?'))return;try{await api(`/api/sessions/${encodeURIComponent(id)}/delete`,{});if(state.capture?.id===id)state.capture=null;if(state.session?.id===id){state.session=null;state.replay=null;}await load();toast('Session deleted from the Pi.');}catch(e){toast(e.message,true);}}
async function submit(form,action){const button=form.querySelector('[type="submit"]');button.disabled=true;try{await action();}catch(e){toast(e.message,true);}finally{button.disabled=false;if(form.id==='route-form')button.disabled=state.waypoints.length<2;}}
function page(name){if(name==='main')return;if(!titles[name])name='map';state.page=name;for(const p of Object.keys(titles)){$(`page-${p}`).hidden=p!==name;document.querySelector(`[data-page="${p}"]`).classList.toggle('active',p===name);}[$('breadcrumb').textContent,$('page-title').textContent,$('page-description').textContent]=titles[name];if(name!=='sessions')pause();history.replaceState(null,'',`#${name}`);}
function updateStats(){const h=state.health;$('device-count').textContent=state.map.devices.length;$('point-count').textContent=state.points.length;$('route-count').textContent=`${state.routes.length} saved route${state.routes.length===1?'':'s'}`;$('session-count').textContent=h.sessions;$('record-count').textContent=`${h.records.toLocaleString()} raw records preserved`;$('storage').textContent=bytes(h.history_bytes);$('free-storage').textContent=`${bytes(h.free_bytes)} available on host`;$('connection').textContent='Panel connected';$('connection-dot').className='dot connected';$('updated').textContent=`Synced ${new Date().toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}`;}
async function load(){const button=$('refresh');button.disabled=true;try{const [health,map,pointData,routeData,sessionData]=await Promise.all([api('/api/health'),api('/api/map'),api('/api/points'),api('/api/routes'),api('/api/sessions?offset='+state.offset)]);Object.assign(state,{health,map,points:pointData.points,routes:routeData.routes,sessions:sessionData.sessions,total:sessionData.total});if(health.active_capture)state.capture={id:health.active_capture.session.id,session:health.active_capture.session,paused:health.active_capture.paused,remaining_s:health.active_capture.remaining_s};updateStats();renderMap();renderReferences();renderSessions();renderDevices();renderPointOptions();renderCapture();errorBanner('');if(!$('point-region').options.length){$('point-region').add(new Option('Not assigned','unknown'));for(const r of map.floorplan.rooms)$('point-region').add(new Option(r.id,r.id));}if(state.session)await selectSession(state.session.id);}catch(e){$('connection').textContent='Connection unavailable';$('connection-dot').className='dot disconnected';errorBanner(`Could not refresh workspace: ${e.message}. Displayed data may be stale. Use Refresh to retry.`);}finally{button.disabled=false;}}
function transform(){const [lo,hi]=state.map.floorplan.bounds_m;const scale=780/Math.max(hi[0]-lo[0],hi[1]-lo[1]);return {scale,cx:(lo[0]+hi[0])/2,cy:(lo[1]+hi[1])/2};}
function xy(x,y){const t=transform();return [500+(x-t.cx)*t.scale,465-(y-t.cy)*t.scale];}
function unxy(x,y){const t=transform();return [t.cx+(x-500)/t.scale,t.cy-(y-465)/t.scale];}
function marker(label,x,y,kind,callback,index){const [px,py]=xy(x,y);const group=svg('g',{class:'map-marker',role:'button',tabindex:0,'aria-label':label,transform:`translate(${px} ${py})`});group.append(svg('circle',{r:22,fill:kind==='device'?'#e5eddf':'#fff5e4',stroke:'#fff','stroke-width':4}),svg('circle',{r:kind==='device'?9:10,fill:kind==='device'?'#427454':'#d5a354'}),svg('title',{},label));if(kind==='device')group.append(svg('path',{d:'M -5 -1 Q 0 -6 5 -1 M -8 -5 Q 0 -12 8 -5',fill:'none',stroke:'#fff','stroke-width':1.6}));else if(index)group.append(svg('text',{'text-anchor':'middle',y:4,'font-size':11,fill:'white'},index));const activate=event=>{event.stopPropagation();callback();};group.addEventListener('click',activate);group.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();activate(event);}});return group;}
function drawRoute(parent,route,active=false){const points=route.context?.point_snapshots||route.points.map(id=>state.points.find(p=>p.id===id)).filter(Boolean);if(points.length<2)return;parent.append(svg('polyline',{points:points.map(p=>xy(p.x,p.y).join(',')).join(' '),class:'route-line'+(active?' active':'')}));}
function renderMap(){if(!state.map)return;const map=$('map-svg');map.replaceChildren();const size=1000/state.zoom;map.setAttribute('viewBox',`${500-size/2} ${470-size/2} ${size} ${size}`);const geometry=svg('g');for(const room of state.map.floorplan.rooms){const edges=new Map();for(const tri of room.floor_triangles_m){geometry.append(svg('polygon',{points:tri.map(p=>xy(...p).join(',')).join(' '),class:'room-shape'}));for(let i=0;i<tri.length;i++){const a=tri[i],b=tri[(i+1)%tri.length];const key=[a.map(v=>v.toFixed(4)).join(','),b.map(v=>v.toFixed(4)).join(',')].sort().join('|');if(edges.has(key))edges.delete(key);else edges.set(key,[a,b]);}}for(const [a,b] of edges.values()){if(Math.abs(a[0]-b[0])>1e-3&&Math.abs(a[1]-b[1])>1e-3)continue;const p=xy(...a),q=xy(...b);geometry.append(svg('line',{x1:p[0],y1:p[1],x2:q[0],y2:q[1],class:'room-border'}));}const [x,y]=xy(...room.label_position_m);geometry.append(svg('text',{x,y,class:'room-label'},room.id));}map.append(geometry);for(const route of state.routes)drawRoute(map,route);drawRoute(map,{points:state.waypoints},true);
for(const device of state.map.devices){const p=device.position_m;map.append(marker(device.model,p.x,p.y,'device',()=>inspectDevice(device)));const [x,y]=xy(p.x,p.y);map.append(svg('text',{x:x+30,y:y+5,class:'device-label'},device.model.replace('ASUS ','').replace('TP-Link ','').replace(' AC750','')));}
for(const [i,p] of state.points.entries()){map.append(marker(`Reference point: ${p.label}`,p.x,p.y,'point',()=>selectPoint(p),i+1));const [x,y]=xy(p.x,p.y);map.append(svg('text',{x:x+27,y:y-18,class:'point-label'},p.label.length>23?p.label.slice(0,21)+'…':p.label));}
if(state.draft){const [x,y]=xy(...state.draft);map.append(svg('circle',{cx:x,cy:y,r:17,fill:'#e5b97266',stroke:'#be873e','stroke-width':3,'stroke-dasharray':'4 3'}));}
}
function details(title,lines,note){setMode('inspect');$('inspect-content').replaceChildren();const box=element('div',undefined,'inspect-details');box.append(element('div','⌖','empty-icon'),element('h3',title));const dl=element('dl');for(const [label,value] of lines){dl.append(element('dt',label),element('dd',value));}box.append(dl);if(note)box.append(element('div',note,'note'));$('inspect-content').append(box);}
function inspectDevice(device){details(device.model,[['Map region',device.map_region],['Approximate position',`${num(device.position_m.x,2)}, ${num(device.position_m.y,2)} m`],['Height above floor',device.height_range_m?`${device.height_range_m.join('–')} m (approx.)`:`${device.position_m.height} m (approx.)`],['Placement',device.placement_notes]],device.id==='asus-router'?'CSI capture verified on the documented firmware. Current connectivity is not monitored.':'Placement is documented. Working CSI acquisition is not verified on this device.');}
function selectPoint(point){if(state.mode==='route'){state.waypoints.push(point.id);renderWaypoints();renderMap();return;}details(point.label,[['Region',point.region],['Reference coordinates',`${num(point.x,3)}, ${num(point.y,3)} m`],['Notes',point.notes||'None']], 'User-defined reference point, not a detected position.');$('annotation-point').value=point.id;}
function setMode(mode){state.mode=mode;state.draft=null;if(mode!=='route')state.waypoints=[];for(const id of ['inspect','point','route']){$(`mode-${id}`).classList.toggle('selected',id===mode);$(`mode-${id}`).setAttribute('aria-pressed',id===mode);}$('inspect-content').hidden=mode!=='inspect';$('point-form').hidden=mode!=='point';$('route-form').hidden=mode!=='route';$('inspector-title').textContent=mode==='point'?'New reference point':mode==='route'?'Plan a route':'Your experiment space';$('map-hint').textContent=mode==='point'?'Click inside the scan to place your reference point.':mode==='route'?'Select saved points in walking order.':'Select a device or reference point to inspect it.';if(mode==='route'){state.waypoints=[];renderWaypoints();}renderMap();}
function renderWaypoints(){$('route-waypoints').replaceChildren(...state.waypoints.map(id=>element('li',state.points.find(p=>p.id===id)?.label||id)));$('save-route').disabled=state.waypoints.length<2;$('route-undo').disabled=!state.waypoints.length;if(!state.waypoints.length)$('route-waypoints').append(element('li','Choose at least two saved points.'));}
function renderReferences(){$('reference-count').textContent=state.points.length+state.routes.length;const isPoints=state.references==='points';$('show-points').classList.toggle('selected',isPoints);$('show-routes').classList.toggle('selected',!isPoints);const list=isPoints?state.points:state.routes;$('reference-list').replaceChildren();if(!list.length){empty('reference-list',isPoints?'No points yet. Add your first reference on the map.':'No routes yet. Save two points, then plan a route.');return;}list.forEach((item,i)=>{const button=element('button',undefined,'reference-item');button.append(element('span',isPoints?String(i+1).padStart(2,'0'):'↗','number'));const copy=element('span');copy.append(element('strong',item.label),element('small',isPoints?`${item.region} · ${num(item.x,2)}, ${num(item.y,2)} m`:`${item.points.length} waypoints · planned route`));button.append(copy);button.onclick=()=>{if(isPoints)selectPoint(item);else{details(item.label,[['Waypoints',item.points.map(id=>state.points.find(p=>p.id===id)?.label||id).join(' → ')],['Notes',item.notes||'None']],'Planned reference route. Timing and measured location are not inferred.');drawRoute($('map-svg'),item,true);}};$('reference-list').append(button);});}
function renderPointOptions(){const previous=$('annotation-point').value;$('annotation-point').replaceChildren(new Option('No point',''));for(const p of state.points)$('annotation-point').add(new Option(`${p.label} · ${p.region}`,p.id));if(state.points.some(p=>p.id===previous))$('annotation-point').value=previous;}
function statusTag(status){return element('span',status,'status-tag'+(status==='captured'?'':' bad'));}
function renderSessions(){$('library-count').textContent=state.total;const term=$('session-search').value.toLowerCase(),filter=$('session-filter').value;const filtered=state.sessions.filter(s=>(filter==='all'||s.status===filter)&&`${s.id} ${date(s.started)}`.toLowerCase().includes(term));$('session-list').replaceChildren();if(!filtered.length)empty('session-list','No sessions match this page’s filters.');for(const s of filtered){const button=element('button',undefined,'session-item'+(state.session?.id===s.id?' active':''));button.append(element('strong',s.id.slice(0,8)),statusTag(s.status),element('small',date(s.started)),element('small',`${s.records} records · ${s.annotation_count} labels`));button.onclick=()=>selectSession(s.id);$('session-list').append(button);}$('session-prev').disabled=state.offset===0;$('session-next').disabled=state.offset+100>=state.total;$('session-page').textContent=`${Math.floor(state.offset/100)+1} / ${Math.max(1,Math.ceil(state.total/100))}`;$('recent-sessions').replaceChildren();if(!state.sessions.length)empty('recent-sessions','No recordings have been saved yet.');for(const s of state.sessions.slice(0,3)){const button=element('button',undefined,'recent-session');const title=element('strong',s.id.slice(0,8));title.append(statusTag(s.status));button.append(title,element('small',`${date(s.started)} · ${s.records} records`));button.onclick=()=>{page('sessions');selectSession(s.id);};$('recent-sessions').append(button);}}
async function selectSession(id){pause();const selection=++state.selection;state.session={id};renderCapture();state.replay=null;state.annotations=[];state.position=0;$('annotation-form').hidden=true;$('replay-content').hidden=true;$('add-label').disabled=true;$('export-session').hidden=true;$('replay-message').hidden=false;$('replay-message').textContent='Loading saved measurements…';$('replay-title').textContent=`Session ${id.slice(0,8)}`;$('replay-date').textContent='';empty('annotation-list','Loading labels…');renderSessions();try{const detail=await api(`/api/sessions/${encodeURIComponent(id)}`);if(selection!==state.selection)return;state.session=detail.session;state.annotations=detail.annotations;$('replay-date').textContent=`${date(detail.session.started)} · ${detail.session.status}`;$('export-session').href=`/api/sessions/${encodeURIComponent(id)}/export`;$('export-session').hidden=false;renderAnnotations();const replay=await api(`/api/sessions/${encodeURIComponent(id)}/measurements`);if(selection!==state.selection)return;state.replay=replay;const summary=replay.summary;if(summary.valid_records<2){$('replay-message').textContent=`No usable signal trace. ${summary.records} saved records, ${summary.invalid_records} decode errors. Capture status: ${detail.session.status}.`;return;}$('replay-message').hidden=true;$('replay-content').hidden=false;$('metric-valid').textContent=`${summary.valid_records} / ${summary.records}`;$('metric-rate').textContent=`${num(summary.sample_rate_hz)} Hz`;$('metric-gaps').textContent=summary.gap_count;$('metric-errors').textContent=summary.invalid_records;$('scrubber').max=summary.duration_s;$('scrubber').value=0;$('add-label').disabled=false;$('annotation-start').max=summary.duration_s;$('annotation-end').max=summary.duration_s;renderChart();showPosition();}catch(e){if(selection!==state.selection)return;$('replay-message').hidden=false;$('replay-message').textContent=`Replay unavailable: ${e.message}`;}}
function renderChart(){const chart=$('signal-chart');chart.replaceChildren();const samples=state.replay.samples;const duration=state.replay.summary.duration_s;const valid=samples.filter(s=>s.valid);const max=Math.max(.1,...valid.map(s=>s.step||0),...valid.map(s=>s.smooth||0))*1.12;const x=t=>48+t/duration*734,y=v=>182-v/max*158;for(let i=0;i<=4;i++){const value=max*i/4;chart.append(svg('line',{x1:48,y1:y(value),x2:782,y2:y(value),stroke:'#e9eee3','stroke-dasharray':i?'3 4':''}),svg('text',{x:39,y:y(value)+4,'text-anchor':'end','font-size':10,fill:'#96a18b'},value.toFixed(2)));chart.append(svg('text',{x:x(duration*i/4),y:207,'text-anchor':'middle','font-size':10,fill:'#96a18b'},`${num(duration*i/4)} s`));}for(const a of state.annotations){if(a.end_s===null)continue;chart.append(svg('rect',{x:x(a.start_s),y:24,width:Math.max(1,x(a.end_s)-x(a.start_s)),height:158,fill:a.context?.kind==='planned'?'#dccbb41c':'#a4bd8120'}));}for(const [key,color,width] of [['step','#bdcdb5',1],['smooth','#3f7652',2.2]]){let path='',connected=false;for(const s of samples){if(!s.valid||s[key]===null||s.gap){connected=false;if(!s.valid||s[key]===null)continue;}path+=`${connected?'L':'M'}${x(s.seconds).toFixed(2)},${y(s[key]).toFixed(2)} `;connected=true;}chart.append(svg('path',{d:path,fill:'none',stroke:color,'stroke-width':width,'stroke-linejoin':'round'}));}chart.append(svg('line',{id:'chart-cursor',x1:48,x2:48,y1:20,y2:182,stroke:'#b2894c','stroke-width':1,'stroke-dasharray':'4 3'}));}
function showPosition(){if(!state.replay)return;const t=state.position,duration=state.replay.summary.duration_s;$('scrubber').value=t;$('playback-time').textContent=`${num(t)} / ${num(duration)} s`;$('chart-cursor')?.setAttribute('x1',48+t/duration*734);$('chart-cursor')?.setAttribute('x2',48+t/duration*734);const valid=state.replay.samples.filter(s=>s.valid);let sample=null;for(const s of valid){if(s.seconds>t)break;sample=s;}const stale=!sample||t-sample.seconds>Math.max(.25,(state.replay.summary.median_interval_s||.1)*1.8);$('sample-rms').textContent=stale?'—':num(sample.amplitude_rms,0);$('sample-change').textContent=stale?'—':num(sample.smooth,3);$('sample-state').textContent=stale?'No sample in this gap':`Saved sample #${sample.seq}`;const labels=state.annotations.filter(a=>a.start_s<=t&&(a.end_s===null?a.start_s===t:t<a.end_s));$('active-label').textContent=labels.length?labels.map(a=>`${a.activity} · ${a.context?.kind==='planned'?'planned':'reported'}${a.context?.point_snapshot?' · '+a.context.point_snapshot.label:''}`).join(' / '):'No reference label at this time';}
function pause(){state.playing=false;cancelAnimationFrame(playbackFrame);$('play').textContent='▶ Play';$('play').setAttribute('aria-label','Play session');}
function tick(now){if(!state.playing)return;state.position=Math.min(state.replay.summary.duration_s,state.position+(now-lastPlayback)/1000*Number($('playback-speed').value));lastPlayback=now;showPosition();if(state.position>=state.replay.summary.duration_s){pause();return;}playbackFrame=requestAnimationFrame(tick);}
function renderAnnotations(){$('annotation-list').replaceChildren();if(!state.annotations.length){empty('annotation-list','No labels in this session. Add observations only when you know what happened.');return;}for(const a of state.annotations){const row=element('div',undefined,'annotation-row');const copy=element('div');copy.append(element('strong',a.activity),element('small',`${a.context?.kind||'legacy label'} · ${a.context?.point_snapshot?.label||'No point snapshot'} · timing ±${a.context?.timing_uncertainty_s??'unknown'} s`));if(a.notes)copy.append(element('small',a.notes));const button=element('button',`${num(a.start_s)}–${num(a.end_s)} s`);button.onclick=()=>{if(state.replay){pause();state.position=a.start_s;showPosition();}};row.append(copy,button);$('annotation-list').append(row);}}
function renderDevices(){$('device-grid').replaceChildren();for(const d of state.map.devices){const card=element('article',undefined,'device-card');card.append(element('span',d.map_region,'eyebrow'),element('h3',d.model),element('span',d.id==='asus-router'?'CSI verified · documented firmware':'CSI acquisition not verified','tag'),element('p',d.placement_notes));const b=element('button','Show on map ↗');b.onclick=()=>{page('map');inspectDevice(d);};card.append(b);$('device-grid').append(card);}$('system-details').replaceChildren();for(const [key,value] of [['Panel connection','Connected · local API'],['Current source state','Not monitored · recording paused'],['History database',bytes(state.health.history_bytes)],['Free disk space',bytes(state.health.free_bytes)],['Map revision',state.map.sources.floorplan_sha256.slice(0,16)],['Device layout revision',state.map.sources.devices_sha256.slice(0,16)]])$('system-details').append(element('dt',key),element('dd',value));}
applyTheme(localStorage.getItem('ruview-theme')||'light');$('theme-toggle').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');for(const button of document.querySelectorAll('[data-page]'))button.onclick=()=>page(button.dataset.page);
window.addEventListener('hashchange',()=>page(location.hash.slice(1)));
$('refresh').onclick=load;$('all-sessions').onclick=()=>page('sessions');
for(const mode of ['inspect','point','route'])$(`mode-${mode}`).onclick=()=>setMode(mode);
$('begin-point').onclick=()=>setMode('point');$('cancel-point').onclick=()=>setMode('inspect');$('cancel-route').onclick=()=>setMode('inspect');
$('zoom-in').onclick=()=>{state.zoom=Math.min(2.2,state.zoom+.2);renderMap();};$('zoom-out').onclick=()=>{state.zoom=Math.max(.7,state.zoom-.2);renderMap();};$('zoom-reset').onclick=()=>{state.zoom=1;renderMap();};
$('map-svg').addEventListener('click',event=>{if(state.mode!=='point'||!state.map)return;const pt=$('map-svg').createSVGPoint();pt.x=event.clientX;pt.y=event.clientY;const local=pt.matrixTransform($('map-svg').getScreenCTM().inverse());const [x,y]=unxy(local.x,local.y);const [lo,hi]=state.map.floorplan.bounds_m;if(x<lo[0]||x>hi[0]||y<lo[1]||y>hi[1]){toast('Choose a point inside the scan bounds.',true);return;}state.draft=[x,y];$('point-x').value=x.toFixed(3);$('point-y').value=y.toFixed(3);renderMap();});
$('point-form').onsubmit=event=>{event.preventDefault();submit(event.currentTarget,async()=>{await api('/api/points',{label:$('point-label').value,region:$('point-region').value,x:Number($('point-x').value),y:Number($('point-y').value),notes:$('point-notes').value});state.points=(await api('/api/points')).points;$('point-form').reset();setMode('inspect');renderReferences();renderPointOptions();updateStats();toast('Reference point saved.');});};
$('route-form').onsubmit=event=>{event.preventDefault();submit(event.currentTarget,async()=>{await api('/api/routes',{label:$('route-label').value,points:state.waypoints});state.routes=(await api('/api/routes')).routes;$('route-form').reset();setMode('inspect');state.references='routes';renderReferences();updateStats();toast('Planned route saved.');});};
$('route-undo').onclick=()=>{state.waypoints.pop();renderWaypoints();renderMap();};
$('show-points').onclick=()=>{state.references='points';renderReferences();};$('show-routes').onclick=()=>{state.references='routes';renderReferences();};
$('session-search').oninput=renderSessions;$('session-filter').onchange=renderSessions;
async function sessionPage(offset){try{const data=await api('/api/sessions?offset='+offset);state.offset=offset;state.sessions=data.sessions;state.total=data.total;renderSessions();}catch(e){toast(e.message,true);}}
$('session-prev').onclick=()=>sessionPage(Math.max(0,state.offset-100));$('session-next').onclick=()=>sessionPage(state.offset+100);
$('capture-start').onclick=startCapture;$('capture-pause').onclick=()=>captureAction('pause');$('capture-resume').onclick=()=>captureAction('resume');$('capture-stop').onclick=()=>captureAction('stop');$('capture-delete').onclick=()=>deleteSession(state.capture?.id||state.session?.id);renderCapture();
$('play').onclick=()=>{if(!state.replay)return;if(state.playing){pause();return;}if(state.position>=state.replay.summary.duration_s)state.position=0;state.playing=true;lastPlayback=performance.now();$('play').textContent='Ⅱ Pause';$('play').setAttribute('aria-label','Pause session');playbackFrame=requestAnimationFrame(tick);};
$('scrubber').oninput=()=>{pause();state.position=Number($('scrubber').value);showPosition();};
$('add-label').onclick=()=>{$('annotation-form').hidden=false;$('annotation-start').value=state.position.toFixed(3);$('annotation-end').value=Math.min(state.position+1,state.replay.summary.duration_s).toFixed(3);$('annotation-start').focus();};$('cancel-label').onclick=()=>{$('annotation-form').hidden=true;};
$('annotation-form').onsubmit=event=>{event.preventDefault();submit(event.currentTarget,async()=>{const sid=state.session.id;await api(`/api/sessions/${encodeURIComponent(sid)}/annotations`,{start_s:Number($('annotation-start').value),end_s:Number($('annotation-end').value),activity:$('annotation-activity').value,point_id:$('annotation-point').value||null,kind:$('annotation-kind').value,timing_uncertainty_s:$('annotation-uncertainty').value===''?null:Number($('annotation-uncertainty').value),notes:$('annotation-notes').value});state.annotations=(await api(`/api/sessions/${encodeURIComponent(sid)}`)).annotations;renderAnnotations();renderChart();showPosition();$('annotation-form').hidden=true;$('annotation-form').reset();const item=state.sessions.find(s=>s.id===sid);if(item)item.annotation_count=state.annotations.length;renderSessions();toast('Activity label saved to this session.');});};
page(location.hash.slice(1)||'map');load();
